In [ ]:
# prompt: charge le fichier excel Donées de prédictions

import pandas as pd

# Replace 'Donées de prédictions.xlsx' with the actual file name if different
# Replace '/content/drive/MyDrive/...' with the actual path to your file in Google Drive
try:
  df = pd.read_excel('/content/sample_data/Données de prédictions.xlsx')
  print(df.head()) # Display the first few rows to confirm successful loading
except FileNotFoundError:
  print("Error: File not found. Please check the file path.")
except Exception as e:
  print(f"An error occurred: {e}")

      Années   Trimestres  Passagers     PIB Réel  Coût mondial du pétrole  \
0 2024-12-01  Trimestre 4        NaN  6403.843286                58.451460
1 2025-03-01  Trimestre 1        NaN  6515.813574                65.521859
2 2025-06-01  Trimestre 2        NaN  6537.031760                74.666757
3 2025-09-01  Trimestre 3        NaN  6639.770234                68.656888
4 2025-12-01  Trimestre 4        NaN  6589.510538                70.455783

   Dépense de consommation individuellle des ménages  Exportations  \
0                                          98.522012    815.032424
1                                          98.354539    711.604332
2                                          98.190707    802.772398
3                                          98.025054    879.372662
4                                          97.857581    875.666585

   Importations  PIB par habitant  Covid-19  Reprise du trafic
0   1382.464065       1641.684478         0                  0
1   1415.706017       1645.376033         0                  0
2   1545.676518       1649.067589         0                  0
3   1526.593862       1652.759145         0                  0
4   1527.623470       1656.450701         0                  0

In [ ]:
# prompt: Introduit des variables saisonnières booléenne trimestrielles (0; 1) dans le dataframe en t'appuyant sur la colonne Années

import pandas as pd

# Replace 'Donées de prédictions.xlsx' with the actual file name if different
# Replace '/content/drive/MyDrive/...' with the actual path to your file in Google Drive
try:
  df = pd.read_excel('/content/sample_data/Données de prédictions.xlsx')

  # Assuming the 'Années' column contains the year information
  df['Trimestre'] = (df['Années'].dt.quarter) # Extract quarter from the date

  # Create seasonal dummy variables
  df['Saison_T1'] = (df['Trimestre'] == 1).astype(int)
  df['Saison_T2'] = (df['Trimestre'] == 2).astype(int)
  df['Saison_T3'] = (df['Trimestre'] == 3).astype(int)
  df['Saison_T4'] = (df['Trimestre'] == 4).astype(int)

  print(df.head()) # Display the first few rows to confirm successful loading
except FileNotFoundError:
  print("Error: File not found. Please check the file path.")
except KeyError:
    print("Error: 'Années' column not found in the DataFrame. Please check the column name.")
except AttributeError:
    print("Error: 'Années' column does not appear to contain datetime objects. Please ensure correct data type.")
except Exception as e:
  print(f"An error occurred: {e}")

      Années   Trimestres  Passagers     PIB Réel  Coût mondial du pétrole  \
0 2024-12-01  Trimestre 4        NaN  6403.843286                58.451460
1 2025-03-01  Trimestre 1        NaN  6515.813574                65.521859
2 2025-06-01  Trimestre 2        NaN  6537.031760                74.666757
3 2025-09-01  Trimestre 3        NaN  6639.770234                68.656888
4 2025-12-01  Trimestre 4        NaN  6589.510538                70.455783

   Dépense de consommation individuellle des ménages  Exportations  \
0                                          98.522012    815.032424
1                                          98.354539    711.604332
2                                          98.190707    802.772398
3                                          98.025054    879.372662
4                                          97.857581    875.666585

   Importations  PIB par habitant  Covid-19  Reprise du trafic  Trimestre  \
0   1382.464065       1641.684478         0                  0          4
1   1415.706017       1645.376033         0                  0          1
2   1545.676518       1649.067589         0                  0          2
3   1526.593862       1652.759145         0                  0          3
4   1527.623470       1656.450701         0                  0          4

   Saison_T1  Saison_T2  Saison_T3  Saison_T4
0          0          0          0          1
1          1          0          0          0
2          0          1          0          0
3          0          0          1          0
4          0          0          0          1

In [ ]:
# prompt: Considère les variables Covid-19 et Reprise du trafic comme des variables booléennes 0 et 1

import pandas as pd

# Replace 'Donées de prédictions.xlsx' with the actual file name if different
# Replace '/content/drive/MyDrive/...' with the actual path to your file in Google Drive
try:
  df = pd.read_excel('/content/sample_data/Données de prédictions.xlsx')

  # Assuming the 'Années' column contains the year information
  df['Trimestre'] = (df['Années'].dt.quarter) # Extract quarter from the date

  # Create seasonal dummy variables
  df['Saison_T1'] = (df['Trimestre'] == 1).astype(int)
  df['Saison_T2'] = (df['Trimestre'] == 2).astype(int)
  df['Saison_T3'] = (df['Trimestre'] == 3).astype(int)
  df['Saison_T4'] = (df['Trimestre'] == 4).astype(int)

  # Convert 'Covid-19' and 'Reprise du trafic' to boolean (0 or 1)
  # Replace 'Covid-19' and 'Reprise du trafic' with the actual column names if they are different
  df['Covid-19'] = df['Covid-19'].astype(int)  # Convert to integer (0 or 1)
  df['Reprise du trafic'] = df['Reprise du trafic'].astype(int) # Convert to integer (0 or 1)


  print(df.head()) # Display the first few rows to confirm successful loading
except FileNotFoundError:
  print("Error: File not found. Please check the file path.")
except KeyError as e:
    print(f"Error: Column '{e}' not found in the DataFrame. Please check the column name.")
except AttributeError:
    print("Error: 'Années' column does not appear to contain datetime objects. Please ensure correct data type.")
except Exception as e:
  print(f"An error occurred: {e}")

      Années   Trimestres  Passagers     PIB Réel  Coût mondial du pétrole  \
0 2024-12-01  Trimestre 4        NaN  6403.843286                58.451460
1 2025-03-01  Trimestre 1        NaN  6515.813574                65.521859
2 2025-06-01  Trimestre 2        NaN  6537.031760                74.666757
3 2025-09-01  Trimestre 3        NaN  6639.770234                68.656888
4 2025-12-01  Trimestre 4        NaN  6589.510538                70.455783

   Dépense de consommation individuellle des ménages  Exportations  \
0                                          98.522012    815.032424
1                                          98.354539    711.604332
2                                          98.190707    802.772398
3                                          98.025054    879.372662
4                                          97.857581    875.666585

   Importations  PIB par habitant  Covid-19  Reprise du trafic  Trimestre  \
0   1382.464065       1641.684478         0                  0          4
1   1415.706017       1645.376033         0                  0          1
2   1545.676518       1649.067589         0                  0          2
3   1526.593862       1652.759145         0                  0          3
4   1527.623470       1656.450701         0                  0          4

   Saison_T1  Saison_T2  Saison_T3  Saison_T4
0          0          0          0          1
1          1          0          0          0
2          0          1          0          0
3          0          0          1          0
4          0          0          0          1

In [ ]:
# prompt: Applique your_scaler.pkl sur df avec sklearn.preprocessing.Transformer

import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib

# Load the scaler
try:
    your_scaler = joblib.load('/content/sample_data/your_scaler.pkl') # Replace with the actual path to your scaler file
except FileNotFoundError:
    print("Error: 'your_scaler.pkl' not found. Please check the file path.")
    exit() # Exit the script if the scaler file is not found
except Exception as e:
    print(f"An error occurred while loading the scaler: {e}")
    exit()


# Replace 'Donées de prédictions.xlsx' with the actual file name if different
# Replace '/content/drive/MyDrive/...' with the actual path to your file in Google Drive
try:
    df = pd.read_excel('/content/sample_data/Données de prédictions.xlsx')

    # Assuming the 'Années' column contains the year information
    df['Trimestre'] = (df['Années'].dt.quarter) # Extract quarter from the date

    # Create seasonal dummy variables
    df['Saison_T1'] = (df['Trimestre'] == 1).astype(int)
    df['Saison_T2'] = (df['Trimestre'] == 2).astype(int)
    df['Saison_T3'] = (df['Trimestre'] == 3).astype(int)
    df['Saison_T4'] = (df['Trimestre'] == 4).astype(int)

    # Convert 'Covid-19' and 'Reprise du trafic' to boolean (0 or 1)
    # Replace 'Covid-19' and 'Reprise du trafic' with the actual column names if they are different
    df['Covid-19'] = df['Covid-19'].astype(int)  # Convert to integer (0 or 1)
    df['Reprise du trafic'] = df['Reprise du trafic'].astype(int) # Convert to integer (0 or 1)

    # Select columns to scale (excluding non-numeric columns and the target variable)
    columns_to_scale = ['Passagers', 'PIB Réel', 'Coût mondial du pétrole', 'Exportations', 'Importations','PIB par habitant', 'Saison_T1', 'Saison_T2', 'Saison_T3', 'Saison_T4', 'Covid-19', 'Reprise du trafic']

    # Apply the scaler
    df_scaled = pd.DataFrame(your_scaler.transform(df[columns_to_scale]), columns=columns_to_scale, index=df.index)

    #Concatenate scaled features with original dataframe
    df = pd.concat([df.drop(columns_to_scale, axis=1), df_scaled], axis=1)

    print(df.head())

except FileNotFoundError:
    print("Error: File not found. Please check the file path.")
except KeyError as e:
    print(f"Error: Column '{e}' not found in the DataFrame. Please check the column name.")
except AttributeError:
    print("Error: 'Années' column does not appear to contain datetime objects. Please ensure correct data type.")
except ValueError as e:
    print(f"Value Error: {e}") # Handle potential ValueErrors during scaling
except Exception as e:
    print(f"An error occurred: {e}")

      Années   Trimestres  Dépense de consommation individuellle des ménages  \
0 2024-12-01  Trimestre 4                                          98.522012
1 2025-03-01  Trimestre 1                                          98.354539
2 2025-06-01  Trimestre 2                                          98.190707
3 2025-09-01  Trimestre 3                                          98.025054
4 2025-12-01  Trimestre 4                                          97.857581

   Trimestre  Passagers  PIB Réel  Coût mondial du pétrole  Exportations  \
0          4        NaN  1.775270                -0.397618      1.369581
1          1        NaN  2.041490                -0.012834      0.697519
2          2        NaN  2.091938                 0.484849      1.289917
3          3        NaN  2.336208                 0.157780      1.787656
4          4        NaN  2.216711                 0.255680      1.763575

   Importations  PIB par habitant  Saison_T1  Saison_T2  Saison_T3  Saison_T4  \
0      1.737241          1.188052  -0.588348  -0.588348  -0.588348   1.837117
1      1.882576          1.237671   1.699673  -0.588348  -0.588348  -0.544331
2      2.450814          1.287289  -0.588348   1.699673  -0.588348  -0.544331
3      2.367384          1.336908  -0.588348  -0.588348   1.699673  -0.544331
4      2.371885          1.386527  -0.588348  -0.588348  -0.588348   1.837117

   Covid-19  Reprise du trafic
0 -0.359211          -0.306186
1 -0.359211          -0.306186
2 -0.359211          -0.306186
3 -0.359211          -0.306186
4 -0.359211          -0.306186

In [ ]:
# prompt: Applique elastic net tuned sauvegardé à df afin de générer les résultats des prévisions de la variables Passagers en fonctions des prédicteurs suivants : Saison_T1, Saison_T2, Saison_T3, Saison_T4, PIB Réel, Coût mondial du pétrole, Exportations, Importations, PIB par habitant, Covid-19, Reprise du trafic et affiche df

import pandas as pd
import joblib

# Load the trained Elastic Net model
try:
    elastic_net_model = joblib.load('/content/sample_data/elastic_net_tuned.joblib') # Replace with the actual path
except FileNotFoundError:
    print("Error: 'elastic_net_model.pkl' not found. Please check the file path.")
    exit()
except Exception as e:
    print(f"An error occurred while loading the model: {e}")
    exit()

# Assuming 'df' is already loaded and preprocessed as in the previous code
# ... (previous code for data loading and preprocessing)

# Define features (X) and target (y)
features = ['Saison_T1', 'Saison_T2', 'Saison_T3', 'Saison_T4', 'PIB Réel', 'Coût mondial du pétrole', 'Exportations', 'Importations', 'PIB par habitant', 'Covid-19', 'Reprise du trafic']
X = df[features]

# Make predictions
try:
    df['Passagers_predicted'] = elastic_net_model.predict(X)
    print(df) # Display the DataFrame with predictions
except ValueError as e:
    print(f"Prediction Error: {e}") # Handle potential ValueErrors during prediction
except Exception as e:
    print(f"An error occurred during prediction: {e}")

       Années   Trimestres  Dépense de consommation individuellle des ménages  \
0  2024-12-01  Trimestre 4                                          98.522012
1  2025-03-01  Trimestre 1                                          98.354539
2  2025-06-01  Trimestre 2                                          98.190707
3  2025-09-01  Trimestre 3                                          98.025054
4  2025-12-01  Trimestre 4                                          97.857581
5  2026-03-01  Trimestre 1                                          97.690108
6  2026-06-01  Trimestre 2                                          97.526276
7  2026-09-01  Trimestre 3                                          97.360623
8  2026-12-01  Trimestre 4                                          97.193150
9  2027-03-01  Trimestre 1                                          97.025677
10 2027-06-01  Trimestre 2                                          96.861845
11 2027-09-01  Trimestre 3                                          96.696192
12 2027-12-01  Trimestre 4                                          96.528719
13 2028-03-01  Trimestre 1                                          96.361246
14 2028-06-01  Trimestre 2                                          96.195594
15 2028-09-01  Trimestre 3                                          96.029941
16 2028-12-01  Trimestre 4                                          95.862468
17 2029-03-01  Trimestre 1                                          95.694995
18 2029-06-01  Trimestre 2                                          95.531163
19 2029-09-01  Trimestre 3                                          95.365510
20 2029-12-01  Trimestre 4                                          95.198037

    Trimestre  Passagers  PIB Réel  Coût mondial du pétrole  Exportations  \
0           4        NaN  1.775270                -0.397618      1.369581
1           1        NaN  2.041490                -0.012834      0.697519
2           2        NaN  2.091938                 0.484849      1.289917
3           3        NaN  2.336208                 0.157780      1.787656
4           4        NaN  2.216711                 0.255680      1.763575
5           1        NaN  2.498301                 0.431200      0.719076
6           2        NaN  2.520749                 0.610718      1.728475
7           3        NaN  2.816842                 0.828960      2.145600
8           4        NaN  2.654700                 0.871652      2.157945
9           1        NaN  2.952367                 0.858299      0.685377
10          2        NaN  2.945500                 0.689382      2.202104
11          3        NaN  3.296199                 1.465945      2.468976
12          4        NaN  3.089137                 1.449931      2.552528
13          1        NaN  3.403593                 1.268248      0.596492
14          2        NaN  3.587416                -0.574543      1.682117
15          3        NaN  3.792175                 2.068210      2.189979
16          4        NaN  3.687794                 1.990202      2.164714
17          1        NaN  3.972182                 1.660847      1.492651
18          2        NaN  4.014160                 0.706365      2.085050
19          3        NaN  4.273716                 2.635273      2.582789
20          4        NaN  4.124806                 2.492207      2.558707

    Importations  PIB par habitant  Saison_T1  Saison_T2  Saison_T3  \
0       1.737241          1.188052  -0.588348  -0.588348  -0.588348
1       1.882576          1.237671   1.699673  -0.588348  -0.588348
2       2.450814          1.287289  -0.588348   1.699673  -0.588348
3       2.367384          1.336908  -0.588348  -0.588348   1.699673
4       2.371885          1.386527  -0.588348  -0.588348  -0.588348
5       2.517155          1.436146   1.699673  -0.588348  -0.588348
6       3.257663          1.485765  -0.588348   1.699673  -0.588348
7       3.076989          1.535383  -0.588348  -0.588348   1.699673
8       3.023716          1.585002  -0.588348  -0.588348  -0.588348
9       3.169299          1.634621   1.699673  -0.588348  -0.588348
10      4.101564          1.684240  -0.588348   1.699673  -0.588348
11      3.810202          1.733859  -0.588348  -0.588348   1.699673
12      3.692222          1.783477  -0.588348  -0.588348  -0.588348
13      3.838707          1.833096   1.699673  -0.588348  -0.588348
14      3.796026          1.882715  -0.588348   1.699673  -0.588348
15      3.751273          1.932334  -0.588348  -0.588348   1.699673
16      3.781125          1.981953  -0.588348  -0.588348  -0.588348
17      3.931967          2.031571   1.699673  -0.588348  -0.588348
18      4.643626          2.081190  -0.588348   1.699673  -0.588348
19      4.490219          2.130809  -0.588348  -0.588348   1.699673
20      4.454442          2.180428  -0.588348  -0.588348  -0.588348

    Saison_T4  Covid-19  Reprise du trafic  Predictions_Passagers  \
0    1.837117 -0.359211          -0.306186               1.094576
1   -0.544331 -0.359211          -0.306186               0.899387
2   -0.544331 -0.359211          -0.306186               1.203252
3   -0.544331 -0.359211          -0.306186               1.733624
4    1.837117 -0.359211          -0.306186               1.312325
5   -0.544331 -0.359211          -0.306186               1.167456
6   -0.544331 -0.359211          -0.306186               1.463999
7   -0.544331 -0.359211          -0.306186               1.982078
8    1.837117 -0.359211          -0.306186               1.534179
9   -0.544331 -0.359211          -0.306186               1.446163
10  -0.544331 -0.359211          -0.306186               1.729730
11  -0.544331 -0.359211          -0.306186               2.240781
12   1.837117 -0.359211          -0.306186               1.760014
13  -0.544331 -0.359211          -0.306186               1.735408
14  -0.544331 -0.359211          -0.306186               1.889330
15  -0.544331 -0.359211          -0.306186               2.376551
16   1.837117 -0.359211          -0.306186               1.967381
17  -0.544331 -0.359211          -0.306186               1.787740
18  -0.544331 -0.359211          -0.306186               2.147110
19  -0.544331 -0.359211          -0.306186               2.629927
20   1.837117 -0.359211          -0.306186               2.196132

    Passagers_predicted
0              1.094576
1              0.899387
2              1.203252
3              1.733624
4              1.312325
5              1.167456
6              1.463999
7              1.982078
8              1.534179
9              1.446163
10             1.729730
11             2.240781
12             1.760014
13             1.735408
14             1.889330
15             2.376551
16             1.967381
17             1.787740
18             2.147110
19             2.629927
20             2.196132

In [ ]:
# prompt: supprime la colonne Passagers_Predicted et affiche df

# Drop the 'Passagers_Predicted' column if it exists
if 'Passagers_predicted' in df.columns:
    df = df.drop('Passagers_predicted', axis=1)

df

,Années,Trimestres,Dépense de consommation individuellle des ménages,Trimestre,Passagers,PIB Réel,Coût mondial du pétrole,Exportations,Importations,PIB par habitant,Saison_T1,Saison_T2,Saison_T3,Saison_T4,Covid-19,Reprise du trafic,Predictions_Passagers
0,2024-12-01,Trimestre 4,98.522012,4,NaN,1.775270,-0.397618,1.369581,1.737241,1.188052,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186,1.094576
1,2025-03-01,Trimestre 1,98.354539,1,NaN,2.041490,-0.012834,0.697519,1.882576,1.237671,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186,0.899387
2,2025-06-01,Trimestre 2,98.190707,2,NaN,2.091938,0.484849,1.289917,2.450814,1.287289,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186,1.203252
3,2025-09-01,Trimestre 3,98.025054,3,NaN,2.336208,0.157780,1.787656,2.367384,1.336908,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186,1.733624
4,2025-12-01,Trimestre 4,97.857581,4,NaN,2.216711,0.255680,1.763575,2.371885,1.386527,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186,1.312325
5,2026-03-01,Trimestre 1,97.690108,1,NaN,2.498301,0.431200,0.719076,2.517155,1.436146,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186,1.167456
6,2026-06-01,Trimestre 2,97.526276,2,NaN,2.520749,0.610718,1.728475,3.257663,1.485765,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186,1.463999
7,2026-09-01,Trimestre 3,97.360623,3,NaN,2.816842,0.828960,2.145600,3.076989,1.535383,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186,1.982078
8,2026-12-01,Trimestre 4,97.193150,4,NaN,2.654700,0.871652,2.157945,3.023716,1.585002,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186,1.534179
9,2027-03-01,Trimestre 1,97.025677,1,NaN,2.952367,0.858299,0.685377,3.169299,1.634621,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186,1.446163
10,2027-06-01,Trimestre 2,96.861845,2,NaN,2.945500,0.689382,2.202104,4.101564,1.684240,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186,1.729730
11,2027-09-01,Trimestre 3,96.696192,3,NaN,3.296199,1.465945,2.468976,3.810202,1.733859,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186,2.240781
12,2027-12-01,Trimestre 4,96.528719,4,NaN,3.089137,1.449931,2.552528,3.692222,1.783477,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186,1.760014
13,2028-03-01,Trimestre 1,96.361246,1,NaN,3.403593,1.268248,0.596492,3.838707,1.833096,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186,1.735408
14,2028-06-01,Trimestre 2,96.195594,2,NaN,3.587416,-0.574543,1.682117,3.796026,1.882715,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186,1.889330
15,2028-09-01,Trimestre 3,96.029941,3,NaN,3.792175,2.068210,2.189979,3.751273,1.932334,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186,2.376551
16,2028-12-01,Trimestre 4,95.862468,4,NaN,3.687794,1.990202,2.164714,3.781125,1.981953,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186,1.967381
17,2029-03-01,Trimestre 1,95.694995,1,NaN,3.972182,1.660847,1.492651,3.931967,2.031571,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186,1.787740
18,2029-06-01,Trimestre 2,95.531163,2,NaN,4.014160,0.706365,2.085050,4.643626,2.081190,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186,2.147110
19,2029-09-01,Trimestre 3,95.365510,3,NaN,4.273716,2.635273,2.582789,4.490219,2.130809,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186,2.629927
20,2029-12-01,Trimestre 4,95.198037,4,NaN,4.124806,2.492207,2.558707,4.454442,2.180428,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186,2.196132

In [ ]:
# prompt: range les données de la colonne Preditctions_passagers dans la colonne Passagers

# Assuming 'df' is your DataFrame and 'Predictions_passagers' is the correct column name
# Replace 'Predictions_passagers' with the actual column name if it is different

try:
    df['Passagers'] = df['Predictions_Passagers']
    print(df.head()) # Display first few rows to verify
except KeyError:
    print("Error: 'Predictions_passagers' column not found. Please check the column name.")
except Exception as e:
    print(f"An error occurred: {e}")

      Années   Trimestres  Dépense de consommation individuellle des ménages  \
0 2024-12-01  Trimestre 4                                          98.522012
1 2025-03-01  Trimestre 1                                          98.354539
2 2025-06-01  Trimestre 2                                          98.190707
3 2025-09-01  Trimestre 3                                          98.025054
4 2025-12-01  Trimestre 4                                          97.857581

   Trimestre  Passagers  PIB Réel  Coût mondial du pétrole  Exportations  \
0          4   1.094576  1.775270                -0.397618      1.369581
1          1   0.899387  2.041490                -0.012834      0.697519
2          2   1.203252  2.091938                 0.484849      1.289917
3          3   1.733624  2.336208                 0.157780      1.787656
4          4   1.312325  2.216711                 0.255680      1.763575

   Importations  PIB par habitant  Saison_T1  Saison_T2  Saison_T3  Saison_T4  \
0      1.737241          1.188052  -0.588348  -0.588348  -0.588348   1.837117
1      1.882576          1.237671   1.699673  -0.588348  -0.588348  -0.544331
2      2.450814          1.287289  -0.588348   1.699673  -0.588348  -0.544331
3      2.367384          1.336908  -0.588348  -0.588348   1.699673  -0.544331
4      2.371885          1.386527  -0.588348  -0.588348  -0.588348   1.837117

   Covid-19  Reprise du trafic  Predictions_Passagers
0 -0.359211          -0.306186               1.094576
1 -0.359211          -0.306186               0.899387
2 -0.359211          -0.306186               1.203252
3 -0.359211          -0.306186               1.733624
4 -0.359211          -0.306186               1.312325

In [ ]:
# prompt: Supprimes la colonne Predictions_Passagers et affiche df

# Drop the 'Predictions_Passagers' column if it exists
if 'Predictions_Passagers' in df.columns:
    df = df.drop('Predictions_Passagers', axis=1)

df

,Années,Trimestres,Dépense de consommation individuellle des ménages,Trimestre,Passagers,PIB Réel,Coût mondial du pétrole,Exportations,Importations,PIB par habitant,Saison_T1,Saison_T2,Saison_T3,Saison_T4,Covid-19,Reprise du trafic
0,2024-12-01,Trimestre 4,98.522012,4,1.094576,1.775270,-0.397618,1.369581,1.737241,1.188052,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186
1,2025-03-01,Trimestre 1,98.354539,1,0.899387,2.041490,-0.012834,0.697519,1.882576,1.237671,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186
2,2025-06-01,Trimestre 2,98.190707,2,1.203252,2.091938,0.484849,1.289917,2.450814,1.287289,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186
3,2025-09-01,Trimestre 3,98.025054,3,1.733624,2.336208,0.157780,1.787656,2.367384,1.336908,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186
4,2025-12-01,Trimestre 4,97.857581,4,1.312325,2.216711,0.255680,1.763575,2.371885,1.386527,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186
5,2026-03-01,Trimestre 1,97.690108,1,1.167456,2.498301,0.431200,0.719076,2.517155,1.436146,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186
6,2026-06-01,Trimestre 2,97.526276,2,1.463999,2.520749,0.610718,1.728475,3.257663,1.485765,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186
7,2026-09-01,Trimestre 3,97.360623,3,1.982078,2.816842,0.828960,2.145600,3.076989,1.535383,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186
8,2026-12-01,Trimestre 4,97.193150,4,1.534179,2.654700,0.871652,2.157945,3.023716,1.585002,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186
9,2027-03-01,Trimestre 1,97.025677,1,1.446163,2.952367,0.858299,0.685377,3.169299,1.634621,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186
10,2027-06-01,Trimestre 2,96.861845,2,1.729730,2.945500,0.689382,2.202104,4.101564,1.684240,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186
11,2027-09-01,Trimestre 3,96.696192,3,2.240781,3.296199,1.465945,2.468976,3.810202,1.733859,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186
12,2027-12-01,Trimestre 4,96.528719,4,1.760014,3.089137,1.449931,2.552528,3.692222,1.783477,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186
13,2028-03-01,Trimestre 1,96.361246,1,1.735408,3.403593,1.268248,0.596492,3.838707,1.833096,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186
14,2028-06-01,Trimestre 2,96.195594,2,1.889330,3.587416,-0.574543,1.682117,3.796026,1.882715,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186
15,2028-09-01,Trimestre 3,96.029941,3,2.376551,3.792175,2.068210,2.189979,3.751273,1.932334,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186
16,2028-12-01,Trimestre 4,95.862468,4,1.967381,3.687794,1.990202,2.164714,3.781125,1.981953,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186
17,2029-03-01,Trimestre 1,95.694995,1,1.787740,3.972182,1.660847,1.492651,3.931967,2.031571,1.699673,-0.588348,-0.588348,-0.544331,-0.359211,-0.306186
18,2029-06-01,Trimestre 2,95.531163,2,2.147110,4.014160,0.706365,2.085050,4.643626,2.081190,-0.588348,1.699673,-0.588348,-0.544331,-0.359211,-0.306186
19,2029-09-01,Trimestre 3,95.365510,3,2.629927,4.273716,2.635273,2.582789,4.490219,2.130809,-0.588348,-0.588348,1.699673,-0.544331,-0.359211,-0.306186
20,2029-12-01,Trimestre 4,95.198037,4,2.196132,4.124806,2.492207,2.558707,4.454442,2.180428,-0.588348,-0.588348,-0.588348,1.837117,-0.359211,-0.306186

In [ ]:
# prompt: Applique l'inverse de your_scale.pkl à df avec sklearn.preprocessing.Transformer

import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib

# Load the scaler
try:
    your_scaler = joblib.load('/content/sample_data/your_scaler.pkl')
except FileNotFoundError:
    print("Error: 'your_scaler.pkl' not found. Please check the file path.")
    exit()
except Exception as e:
    print(f"An error occurred while loading the scaler: {e}")
    exit()

# Assuming df is already loaded and preprocessed as in your original code
# ... (your code to load and preprocess df)

# Select columns to inverse transform
columns_to_inverse_transform = ['Passagers', 'PIB Réel', 'Coût mondial du pétrole', 'Exportations', 'Importations','PIB par habitant', 'Saison_T1', 'Saison_T2', 'Saison_T3', 'Saison_T4', 'Covid-19', 'Reprise du trafic']

# Apply the inverse transform
try:
    df_inverse_transformed = pd.DataFrame(your_scaler.inverse_transform(df[columns_to_inverse_transform]), columns=columns_to_inverse_transform, index=df.index)

    # Concatenate inverse transformed features with original dataframe
    df = pd.concat([df.drop(columns_to_inverse_transform, axis=1), df_inverse_transformed], axis=1)
    print(df.head())
except ValueError as e:
    print(f"Value Error during inverse transform: {e}")
except Exception as e:
    print(f"An error occurred during inverse transform: {e}")

      Années   Trimestres  Dépense de consommation individuellle des ménages  \
0 2024-12-01  Trimestre 4                                          98.522012
1 2025-03-01  Trimestre 1                                          98.354539
2 2025-06-01  Trimestre 2                                          98.190707
3 2025-09-01  Trimestre 3                                          98.025054
4 2025-12-01  Trimestre 4                                          97.857581

   Trimestre      Passagers     PIB Réel  Coût mondial du pétrole  \
0          4  442292.824327  6403.843286                58.451460
1          1  423011.344202  6515.813574                65.521859
2          2  453028.290641  6537.031760                74.666757
3          3  505420.471480  6639.770234                68.656888
4          4  463802.895286  6589.510538                70.455783

   Exportations  Importations  PIB par habitant  Saison_T1  Saison_T2  \
0    815.032424   1382.464065       1641.684478        0.0        0.0
1    711.604332   1415.706017       1645.376033        1.0        0.0
2    802.772398   1545.676518       1649.067589        0.0        1.0
3    879.372662   1526.593862       1652.759145        0.0        0.0
4    875.666585   1527.623470       1656.450701        0.0        0.0

   Saison_T3  Saison_T4  Covid-19  Reprise du trafic
0        0.0        1.0       0.0                0.0
1        0.0        0.0       0.0                0.0
2        0.0        0.0       0.0                0.0
3        1.0        0.0       0.0                0.0
4        0.0        1.0       0.0                0.0

In [ ]:
# prompt: df

df

,Années,Trimestres,Dépense de consommation individuellle des ménages,Trimestre,Passagers,PIB Réel,Coût mondial du pétrole,Exportations,Importations,PIB par habitant,Saison_T1,Saison_T2,Saison_T3,Saison_T4,Covid-19,Reprise du trafic
0,2024-12-01,Trimestre 4,98.522012,4,442292.824327,6403.843286,58.451460,815.032424,1382.464065,1641.684478,0.0,0.0,0.0,1.0,0.0,0.0
1,2025-03-01,Trimestre 1,98.354539,1,423011.344202,6515.813574,65.521859,711.604332,1415.706017,1645.376033,1.0,0.0,0.0,0.0,0.0,0.0
2,2025-06-01,Trimestre 2,98.190707,2,453028.290641,6537.031760,74.666757,802.772398,1545.676518,1649.067589,0.0,1.0,0.0,0.0,0.0,0.0
3,2025-09-01,Trimestre 3,98.025054,3,505420.471480,6639.770234,68.656888,879.372662,1526.593862,1652.759145,0.0,0.0,1.0,0.0,0.0,0.0
4,2025-12-01,Trimestre 4,97.857581,4,463802.895286,6589.510538,70.455783,875.666585,1527.623470,1656.450701,0.0,0.0,0.0,1.0,0.0,0.0
5,2026-03-01,Trimestre 1,97.690108,1,449492.176685,6707.945279,73.680972,714.921963,1560.850446,1660.142256,1.0,0.0,0.0,0.0,0.0,0.0
6,2026-06-01,Trimestre 2,97.526276,2,478785.824366,6717.387026,76.979601,870.264894,1730.223545,1663.833812,0.0,1.0,0.0,0.0,0.0,0.0
7,2026-09-01,Trimestre 3,97.360623,3,529963.654393,6841.921434,80.989792,934.459035,1688.898682,1667.525368,0.0,0.0,1.0,0.0,0.0,0.0
8,2026-12-01,Trimestre 4,97.193150,4,485718.486736,6773.725879,81.774255,936.358747,1676.713939,1671.216924,0.0,0.0,0.0,1.0,0.0,0.0
9,2027-03-01,Trimestre 1,97.025677,1,477023.917898,6898.922676,81.528894,709.735746,1710.012445,1674.908480,1.0,0.0,0.0,0.0,0.0,0.0
10,2027-06-01,Trimestre 2,96.861845,2,505035.775409,6896.034186,78.425050,943.154781,1923.245214,1678.600035,0.0,1.0,0.0,0.0,0.0,0.0
11,2027-09-01,Trimestre 3,96.696192,3,555519.292597,7043.536020,92.694381,984.225420,1856.603357,1682.291591,0.0,0.0,1.0,0.0,0.0,0.0
12,2027-12-01,Trimestre 4,96.528719,4,508027.378040,6956.447146,92.400107,997.083780,1829.618307,1685.983147,0.0,0.0,0.0,1.0,0.0,0.0
13,2028-03-01,Trimestre 1,96.361246,1,505596.668103,7088.705121,89.061690,696.056683,1863.123165,1689.674703,1.0,0.0,0.0,0.0,0.0,0.0
14,2028-06-01,Trimestre 2,96.195594,2,520801.676688,7166.019848,55.200459,863.130485,1853.360811,1693.366258,0.0,1.0,0.0,0.0,0.0,0.0
15,2028-09-01,Trimestre 3,96.029941,3,568931.230098,7252.140136,103.760981,941.288782,1843.124733,1697.057814,0.0,0.0,1.0,0.0,0.0,0.0
16,2028-12-01,Trimestre 4,95.862468,4,528511.800599,7208.238116,102.327575,937.400560,1849.952678,1700.749370,0.0,0.0,0.0,1.0,0.0,0.0
17,2029-03-01,Trimestre 1,95.694995,1,510766.232261,7327.850076,96.275691,833.972468,1884.454131,1704.440926,1.0,0.0,0.0,0.0,0.0,0.0
18,2029-06-01,Trimestre 2,95.531163,2,546266.162204,7345.505824,78.737115,925.140534,2047.228606,1708.132482,0.0,1.0,0.0,0.0,0.0,0.0
19,2029-09-01,Trimestre 3,95.365510,3,593960.633775,7454.673144,114.180748,1001.740798,2012.140474,1711.824037,0.0,0.0,1.0,0.0,0.0,0.0
20,2029-12-01,Trimestre 4,95.198037,4,551108.732062,7392.042744,111.551906,998.034721,2003.957378,1715.515593,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
# prompt: exporte les résultats

# Export the DataFrame to an Excel file
try:
    df.to_excel('predictions_results.xlsx', index=False)  # Save to the current working directory
    print("DataFrame exported successfully to predictions_results.xlsx")
except Exception as e:
    print(f"An error occurred during export: {e}")

# Download the file (optional)
from google.colab import files
files.download('predictions_results.xlsx')

DataFrame exported successfully to predictions_results.xlsx